version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - run: npm run build
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm i
      - run: npm run test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires: [build]
